routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HistoryController;
use App\Models\History;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('home');
});
Route::group(['middleware' => ['auth','admin']], function() {
Route::get('admin', [App\Http\Controllers\admin\PostsController::class, 'admin'])->name('admin');
});
Route::group(['middleware' => ['auth','allstories']], function() {
  Route::resource('allstories', HistoryController::class);
});
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/History.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class History extends Model
{
    use HasFactory;

    // protected $fillable = ['title', 'description','user_id'];
    protected $fillable = [
      'title',
      'description',
      'user_id'
    ];

    public function user() {
      return $this->belongsTo(User::class);
    }

    public function getHistoryUser()
    {
      if ($this->user !== null) {
        return $this->user->name;
      } else {
        return 'не указано';
      }
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function histories() {
      return $this->hasMany(History::class);
    }
    public function isAdmin()
{
return $this->is_admin;
}

}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HistoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\History;
use App\Http\Requests\DataRequest;
use DB;
use Illuminate\Support\Facades\Auth;
use luminate\Auth\Events\Registered;
use Illuminate\Support\Facades\Input;


class HistoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $storiesUser = new History();
   $storiesUser = Auth::user()->histories;

     return view('stories.allstories', ['stories' => $storiesUser->all()]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $stories = new History();
     return view('stories.create', ['stories' => $stories->find(1)]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DataRequest $req)
    {
      $user = Auth::user();
      $stories = History::create([
        'title' => $req->input('title'),
        'description' => $req->input('description'),
        'user_id' => $user->id,
      ]);
    $stories->save();
    return redirect()->route('allstories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\History  $history2
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
      $stories = new History();
        $user = Auth::user()->histories;
     return view('stories.one-stories', ['stories' => $user->find($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\History2  $history2
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $stories = new History();
     return view('stories.update', ['stories' => $stories->find($id)]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\History2  $history2
     * @return \Illuminate\Http\Response
     */
    public function update(DataRequest $req, $id)
    {
      $stories = History::find($id);
      $stories->title = $req->input('title');
      $stories->description = $req->input('description');
    $stories->save();
    return view('stories.one-stories', ['stories' => $stories->find($id)])->with('success', "Запись была обновлена");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\History2  $history2
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
      History::find($id)->delete();
      return redirect()->route('allstories.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }


}

app/Http/Controllers/admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\History;
use App\Http\Requests\DataRequest;
use DB;
use Illuminate\Support\Facades\Auth;
use luminate\Auth\Events\Registered;
use Illuminate\Support\Facades\Input;

class PostsController extends Controller
{
    public function admin() {
      $stories = new History();
        return view('stories.admin', ['stories' => $stories->all()]);
    }
}

resources/views/home.blade.php
@extends("layouts.app")

@section('title-block')
     Главная
@endsection

@section('content')
     <h1>Главная</h1>
     <p>Aptent placerat dignissim praesent nam enim nullam venenatis cursus, nulla semper morbi sed cubilia velit. Nulla suscipit morbi rutrum natoque malesuada consequat inceptos, pharetra tellus torquent semper accumsan fringilla curae integer, vivamus metus faucibus lectus hac vestibulum. Tellus egestas facilisi aliquet vestibulum eleifend phasellus curae, posuere consequat litora laoreet vitae et congue, varius lacinia nisi integer mollis scelerisque. Ultricies tortor sapien himenaeos sit interdum aenean accumsan tempor, facilisi taciti platea venenatis aptent morbi dolor non, inceptos augue vehicula enim diam ridiculus vulputate. Ipsum turpis nisi tincidunt fusce nibh potenti, ligula eros integer malesuada himenaeos hac lectus, semper netus sociosqu cubilia suscipit. Per ullamcorper aliquam tellus volutpat facilisis phasellus morbi, nibh tortor fusce dolor vestibulum primis nullam cursus, vitae potenti enim placerat natoque adipiscing. Facilisis purus eros lectus donec ultricies et posuere ut elementum metus vel parturient, per habitant mollis eu sem eleifend hac pretium morbi suscipit rhoncus eget tempus, dolor class euismod scelerisque est maecenas taciti hendrerit sagittis id ullamcorper.</p>
@endsection

resources/views/inc/app.blade.php
@section('app')
<div class="app">
  <h1>Боковая панель</h1>
  <p>Что-то в боковой панели</p>
</div>

resources/views/inc/footer.blade.php
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">© 2017–2021</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Cool stuff</a></li>
          <li><a class="link-secondary" href="#">Random feature</a></li>
          <li><a class="link-secondary" href="#">Team feature</a></li>
          <li><a class="link-secondary" href="#">Stuff for developers</a></li>
          <li><a class="link-secondary" href="#">Another one</a></li>
          <li><a class="link-secondary" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Resource</a></li>
          <li><a class="link-secondary" href="#">Resource name</a></li>
          <li><a class="link-secondary" href="#">Another resource</a></li>
          <li><a class="link-secondary" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Team</a></li>
          <li><a class="link-secondary" href="#">Locations</a></li>
          <li><a class="link-secondary" href="#">Privacy</a></li>
          <li><a class="link-secondary" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>

resources/views/inc/header.blade.php
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-body border-bottom shadow-sm">
  <p class="h5 my-0 me-md-auto fw-normal">Laravel</p>
  <nav class="my-2 my-md-0 me-md-3">
    <a class="p-2 text-dark" href="/">Главная</a>
  @if(Auth::check() && Auth::user()->isAdmin())
    <a class="p-2 text-dark" href="admin">Админка</a>
    @endif

    @if(Auth::check())
   <a class="p-2 text-dark" href="allstories">Записи</a>
@endif
</nav>
    <nav id="nav2" class="my-2 my-md-0 me-md-3">
        <!-- Authentication Links -->
        @guest
            @if (Route::has('login'))
                    <a class="p-2 text-dark" href="{{ route('login') }}">{{ __('Login') }}</a>
            @endif

            @if (Route::has('register'))
                    <a class="p-2 text-dark" href="{{ route('register') }}">{{ __('Register') }}</a>
            @endif
        @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="p-2 text-dark dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }}
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>
        @endguest
    </nav>
</header>

resources/views/inc/hi.blade.php
<div class="container" id="hi">
  <div class="row">
    <h1>Всем привет на нашем сайте</h1>
    <p>Platea nisi scelerisque porta dui tortor luctus velit sollicitudin, tincidunt tempor dis eget nascetur donec. </p>
  </div>
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title-block')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>

         @include('inc.header')
         <div class="col-12">
         @if(Request::is('/'))
           @include('inc.hi')
         @endif
         </div>
         <div class="container">
           <div class="row">
             <div class="col-8">
               @yield('content')
             </div>
             <div class="col-4">
                 @include('inc.app')
               </div>
           </div>
         </div>




            @include('inc.footer')
</body>
</html>

resources/views/stories/admin.blade.php
@extends("layouts.app")

@section('title-block')
     Админка
@endsection

@section('content')
@auth
     @if(Auth::user()->isAdmin())
     <h1>Админка</h1>

        <table class="table table-hover table-striped">
                       <thead>
                           <th>ID</th>
                           <th>title</th>
                           <th>created_at</th>
                           <th>user_id</th>
                       </thead>
                       <tbody>
                          @foreach($stories as $el)
                           <tr>

                               <td>{{ $el->id }}</td>
                               <td><a href="{{ url('stories-one', $el->id) }}">{{ $el->title }}</a></td>
                               <td>{{ $el->created_at }}</td>
                               <td>{{ $el->user->name }}</td>
                           </tr>
                          @endforeach

                       </tbody>
                   </table>
     @endif
@endauth



@endsection

resources/views/stories/allstories.blade.php
@extends("layouts.app")

@section('title-block')
     Все записи
@endsection

@section('content')
     <h1>Все записи</h1>
      <a href="{{ url('allstories/create') }}"><button class="btn btn-warning">Создать запись</button></a>

        <table class="table table-hover table-striped">
                       <thead>
                           <th>ID</th>
                           <th>title</th>
                           <th>created_at</th>
                           <th>user_id</th>
                       </thead>
                       <tbody>
                          @foreach($stories as $el)
                           <tr>

                               <td>{{ $el->id }}</td>
                               <td><a href="{{ route('allstories.show', $el->id) }}">{{ $el->title }}</a></td>
                               <td>{{ $el->created_at }}</td>
                               <td>{{ $el->user->name }}</td>
                           </tr>
                          @endforeach

                       </tbody>
                   </table>
@endsection

resources/views/stories/create.blade.php
@extends("layouts.app")

@section('title-block')
     Добавить новую запись
@endsection

@section('content')
     <h1>Добавить новую запись</h1>

     @if($errors->any())
        <div class="alert alert-danger">
          <ul>
            @foreach($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>

     @endif

        <form action="{{ route('allstories.store') }}" method="POST">
          @csrf
          <div class="form-group">
            <label for="title">Введите название</label>
            <input value="{{ request()->input('title', old('title')) }}" type="text" name="title" placeholder="Введите название" id="title" class="form-control">
          </div>

          <div class="form-group">
            <label for="description">Введите описание</label>
            <textarea name="description" id="description" class="form-control" placeholder="Описание">{{ request()->input('description', old('description')) }}</textarea>
          </div>
          <div class="form-group">
            <label for="user_id">user_id</label>
            <input value="{{ request()->input('user_id', old('user_id')) }}" type="text" name="user_id" placeholder="Введите название" id="user_id" class="form-control">
          </div>
          <button type="submit" class="btn btn-success">Добавить новую запись</button>
        </form>
@endsection

resources/views/stories/one-stories.blade.php
@extends("layouts.app")

@section('title-block')
     {{ $stories->title }}
@endsection

@section('content')
<h1>{{ $stories->title }}</h1>
   <div class="alert alert-info">
      <p>{{ $stories->description }}</p>
      <p><small>{{ $stories->created_at }}</small></p>
      <p>{{ $stories->user->name }}</p>
      <a href="{{ route('allstories.edit', $stories->id) }}"><button class="btn btn-primary">Редактировать</button></a>
      <form action="{{ route('allstories.destroy', $stories->id ) }}" method="POST">
    @csrf
    @method('DELETE')
      <button class="btn btn-danger">Удалить</button>
</form>
   </div>

@endsection

resources/views/stories/update.blade.php
@extends("layouts.app")

@section('title-block')
     Страница редактирования
@endsection

@section('content')
     <h1>Страница редактирования</h1>
        <form action="{{ route('allstories.show', $stories->id) }}" method="POST">
          @csrf
          <input type="hidden" name="_method" value="PATCH">
          <div class="form-group">
            <label for="title">Введите название</label>
            <input value="{{ $stories->title }}" type="text" name="title" placeholder="Введите название" id="title" class="form-control">
          </div>

          <div class="form-group">
            <label for="description">Введите описание</label>
            <textarea name="description" id="description" class="form-control" placeholder="Описание">{{ $stories->description }}</textarea>
          </div>
          <button type="submit" class="btn btn-success">Обновит</button>
        </form>
@endsection